# This workflow will create a GitHub release every time a tag is pushed
name: Create Web Awesome GitHub Release

on:
  push:
    tags:
      - "v2.*"
      - "v3.*"

defaults:
  run:
    shell: bash
    working-directory: ./packages/webawesome

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
